import { useState } from 'react';
import { fmtDate, money, monthLabel } from '../../lib/format';
import {
  Button, Card, EmptyState, ErrorState, LoadingBlock, Modal, SectionHeader, StatCard, Tabs, useToast,
} from '../../components/ui';
import { fetchSupplierOrders, fetchSupplierStatements } from '../../api/supplier';
import { useAsync } from '../../lib/hooks';
import type { SupplierStatement } from '../../types';

/**
 * Monthly statements.
 *
 * A statement is generated by the shop from the transaction records and shows
 * the month's activity between an opening and closing balance. It is a summary
 * of recorded facts, never a figure typed in by hand — which is why a supplier
 * can rely on it.
 */
export default function SupplierStatements() {
  const { push } = useToast();
  const [open, setOpen] = useState<SupplierStatement | null>(null);
  const [tab, setTab] = useState<'statements' | 'account'>('statements');

  const statements = useAsync(() => fetchSupplierStatements(), []);
  const orders = useAsync(() => fetchSupplierOrders(), []);

  const latest = statements.data?.[0];
  const all = statements.data ?? [];

  const yearTotals = all
    .filter((s) => new Date(s.period_month).getFullYear() === new Date().getFullYear())
    .reduce(
      (acc, s) => ({
        payable: acc.payable + Number(s.total_payable),
        paid: acc.paid + Number(s.total_paid),
        units: acc.units + s.units_sold,
      }),
      { payable: 0, paid: 0, units: 0 },
    );

  return (
    <div className="space-y-4">
      <div>
        <h1 className="text-lg font-semibold text-brand-ink">Statements</h1>
        <p className="text-sm text-brand-muted">
          Monthly summaries built from the recorded transactions — open a month to see the detail.
        </p>
      </div>

      <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">
        <StatCard label="Statements available" value={all.length} />
        <StatCard label="This year: payable" value={money(yearTotals.payable)} tone="brand" sub="Cost of your units sold" />
        <StatCard label="This year: paid" value={money(yearTotals.paid)} tone="good" />
        <StatCard label="This year: units sold" value={yearTotals.units} />
      </div>

      <Tabs
        tabs={[
          { id: 'statements', label: 'By month', count: all.length },
          { id: 'account', label: 'Open balance' },
        ]}
        active={tab}
        onChange={setTab}
      />

      {tab === 'statements' ? (
        statements.loading ? <LoadingBlock rows={5} /> :
        statements.error ? <ErrorState message={statements.error} onRetry={statements.reload} /> :
        all.length === 0 ? (
          <Card>
            <EmptyState
              title="No statements yet"
              description="The shop generates a statement at the end of each month. It will appear here once issued."
            />
          </Card>
        ) : (
          <div className="grid sm:grid-cols-2 xl:grid-cols-3 gap-3">
            {all.map((s) => (
              <Card key={s.id} className={s.outstanding > 0 ? 'border-state-amber/40' : ''}>
                <div className="flex items-start justify-between gap-2">
                  <div>
                    <p className="num text-xs text-brand-muted">{s.statement_number}</p>
                    <p className="font-semibold text-brand-ink">{monthLabel(s.period_month)}</p>
                  </div>
                  <span className={Number(s.outstanding) > 0 ? 'chip-amber' : 'chip-green'}>
                    {Number(s.outstanding) > 0 ? 'Balance open' : 'Settled'}
                  </span>
                </div>

                <dl className="mt-3 space-y-1.5 text-sm">
                  <div className="flex justify-between">
                    <dt className="text-brand-muted">Opening balance</dt>
                    <dd className="num">{money(s.opening_outstanding)}</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-brand-muted">Units sold</dt>
                    <dd className="num">{s.units_sold}</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-brand-muted">Payable this month</dt>
                    <dd className="num">{money(s.total_payable)}</dd>
                  </div>
                  <div className="flex justify-between">
                    <dt className="text-brand-muted">Paid this month</dt>
                    <dd className="num text-state-green">{money(s.total_paid)}</dd>
                  </div>
                  <div className="flex justify-between border-t border-brand-line pt-2">
                    <dt className="font-medium text-brand-ink">Closing balance</dt>
                    <dd className="num font-semibold text-brand-ink">{money(s.outstanding)}</dd>
                  </div>
                </dl>

                <div className="flex items-center justify-between mt-3">
                  <p className="text-xs text-brand-muted">Issued {fmtDate(s.generated_at)}</p>
                  <Button size="sm" variant="secondary" onClick={() => setOpen(s)}>View statement</Button>
                </div>
              </Card>
            ))}
          </div>
        )
      ) : (
        <Card>
          <SectionHeader
            title="Lines still open"
            subtitle="Every payable line with a remaining balance, oldest first."
          />
          {orders.loading ? <LoadingBlock rows={4} /> : (() => {
            const open = (orders.data ?? [])
              .filter((o) => Number(o.outstanding) > 0)
              .sort((a, b) => a.entry_date.localeCompare(b.entry_date));
            if (open.length === 0) {
              return <EmptyState title="Nothing outstanding" description="The account is fully settled." />;
            }
            const total = open.reduce((t, o) => t + Number(o.outstanding), 0);
            return (
              <>
                <p className="text-sm text-brand-charcoal mb-3">
                  <strong className="num">{money(total)} Birr</strong> across {open.length} line
                  {open.length === 1 ? '' : 's'}, the oldest from {fmtDate(open[0].entry_date)}.
                </p>
                <div className="table-wrap">
                  <table className="table">
                    <thead>
                      <tr>
                        <th>Date</th>
                        <th>Product</th>
                        <th>Batch</th>
                        <th className="text-right">Charged</th>
                        <th className="text-right">Paid</th>
                        <th className="text-right">Outstanding</th>
                      </tr>
                    </thead>
                    <tbody>
                      {open.map((o) => (
                        <tr key={o.id}>
                          <td className="text-xs text-brand-muted whitespace-nowrap">{fmtDate(o.entry_date)}</td>
                          <td className="text-brand-ink">{o.product_name}</td>
                          <td className="num text-xs text-brand-charcoal">{o.batch_number}</td>
                          <td className="text-right num">{money(o.payable_amount)}</td>
                          <td className="text-right num text-state-green">{money(o.amount_paid)}</td>
                          <td className="text-right num font-medium">{money(o.outstanding)}</td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </>
            );
          })()}
        </Card>
      )}

      <Modal
        open={Boolean(open)} onClose={() => setOpen(null)}
        title={open ? `Statement ${open.statement_number}` : 'Statement'} size="lg"
        footer={
          <>
            <Button
              variant="secondary"
              onClick={() => {
                if (!open) return;
                void navigator.clipboard.writeText([
                  `LuBella Cosmetics & Accessories — supplier statement`,
                  `Statement: ${open.statement_number}`,
                  `Supplier: ${open.supplier_name}`,
                  `Period: ${monthLabel(open.period_month)}`,
                  ``,
                  `Opening balance: ${money(open.opening_outstanding)} Birr`,
                  `Units sold: ${open.units_sold}`,
                  `Payable this month: ${money(open.total_payable)} Birr`,
                  `Paid this month: ${money(open.total_paid)} Birr`,
                  `Closing balance: ${money(open.outstanding)} Birr`,
                ].join('\n'));
                push({ tone: 'success', title: 'Statement copied' });
              }}
            >
              Copy as text
            </Button>
            <Button variant="ghost" onClick={() => setOpen(null)}>Close</Button>
          </>
        }
      >
        {open && (
          <div className="space-y-4">
            <div className="rounded-xl border border-brand-line p-3">
              <p className="text-sm font-medium text-brand-ink">{open.supplier_name}</p>
              <p className="text-xs text-brand-muted">
                {[open.contact_name, open.phone, open.email].filter(Boolean).join(' · ') || '—'}
              </p>
              {open.address && <p className="text-xs text-brand-muted">{open.address}</p>}
            </div>

            <dl className="space-y-2 text-sm">
              <Row label="Period" value={monthLabel(open.period_month)} />
              <Row label="Opening balance" value={money(open.opening_outstanding)} />
              <Row label="Units sold" value={String(open.units_sold)} />
              <Row label="Payable this month" value={money(open.total_payable)} />
              <Row label="Paid this month" value={money(open.total_paid)} />
              <div className="flex justify-between border-t border-brand-line pt-2">
                <dt className="font-medium text-brand-ink">Closing balance</dt>
                <dd className="num font-semibold text-brand-ink">{money(open.outstanding)}</dd>
              </div>
            </dl>

            <div className="grid grid-cols-3 gap-3">
              <StatCard label="Payable" value={money(open.total_payable)} />
              <StatCard label="Paid" value={money(open.total_paid)} tone="good" />
              <StatCard label="Balance" value={money(open.outstanding)} tone={Number(open.outstanding) > 0 ? 'warn' : 'good'} />
            </div>

            {latest && open.statement_number !== latest.statement_number && (
              <p className="text-xs text-brand-muted">
                This is not the most recent statement. The latest one is {latest.statement_number} for{' '}
                {monthLabel(latest.period_month)}.
              </p>
            )}
          </div>
        )}
      </Modal>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between">
      <dt className="text-brand-muted">{label}</dt>
      <dd className="num text-brand-ink">{value}</dd>
    </div>
  );
}
