#!/usr/bin/env bash
# ============================================================================
# LuBella  |  Build supabase/production_bundle.sql
# ============================================================================
#   scripts/bundle_sql.sh
#
# Concatenates supabase/migrations/*.sql in filename order (9999_api_grants.sql
# therefore comes last, which is required) into a single file that can be pasted
# into the Supabase SQL editor or run with one psql -f.
#
# It deliberately excludes:
#   supabase/local/0000_local_shim.sql   fakes Supabase's auth schema — local only
#   supabase/tests/*.sql                 create fixture data — never on production
# ============================================================================
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$ROOT/supabase/production_bundle.sql"

{
  echo "-- ============================================================================"
  echo "-- LuBella — production bundle (generated $(date +%F) from supabase/migrations/)"
  echo "-- ============================================================================"
  echo "-- Paste this whole file into the Supabase SQL editor on a fresh project, once."
  echo "-- It contains 0001 → 0024 in order and finishes with 9999_api_grants.sql."
  echo "-- Do NOT include supabase/local/0000_local_shim.sql or supabase/tests/*."
  echo "-- Generated by scripts/bundle_sql.sh — regenerate after adding a migration."
  echo "-- ============================================================================"
  echo
  for f in "$ROOT"/supabase/migrations/*.sql; do
    echo
    echo "-- ----------------------------------------------------------------------------"
    echo "-- >>> $(basename "$f")"
    echo "-- ----------------------------------------------------------------------------"
    cat "$f"
  done
} > "$OUT"

echo "✓ $OUT"
echo "  $(grep -c '^-- >>> ' "$OUT") migrations, $(wc -l < "$OUT") lines, $(wc -c < "$OUT") bytes"
